container:
  image: golang:1.9

lint_task:
  env:
    CIRRUS_WORKING_DIR: /go/src/github.com/$CIRRUS_REPO_FULL_NAME

  ci_tools_cache:
    folder: $GOPATH/bin

  get_dep_script: dep version || curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  get_golanci_lint_script: golanci-lint --version || curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.9.3

  dep_cache:
    folder: vendor
    fingerprint_script: cat Gopkg.lock
    populate_script: dep ensure

  lint_script: golangci-lint run


test_task:
  env:
    CIRRUS_WORKING_DIR: /go/src/github.com/$CIRRUS_REPO_FULL_NAME

  container:
    matrix:
      image: golang:latest
      image: golang:1.9
      image: golang:1.10

  ci_tools_cache:
    folder: $GOPATH/bin

  get_dep_script: dep version || curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

  dep_cache:
    folder: vendor
    fingerprint_script: cat Gopkg.lock
    populate_script: dep ensure

  test_script: go test

publish_task:
  only_if: $BRANCH == 'latest' || $BRANCH == 'stable'
  depends_on:
  - test
  - lint
  build_script:
    - docker login -u="nstapelbroekbot" -p="ENCRYPTED[aa19d1b13c4c45c6bda1f837e7330b7514457a26d411a12993f4e8535cbc55b1d13e7ff6c78b4aa63edff97917891a4d]";
    - make build TAGNAME=$BRANCH
    - docker tag nstapelbroek/hostupdater:$BRANCH docker.io/nstapelbroek/hostupdater:$BRANCH
    - docker push docker.io/nstapelbroek/hostupdater
