container:
  image: golang:1.9

lint_task:
  env:
    CIRRUS_WORKING_DIR: /go/src/github.com/$CIRRUS_REPO_FULL_NAME

  ci_tools_cache:
    folder: $GOPATH/bin

  get_dep_script: dep version || curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  get_golanci_lint_script: golanci-lint --version || curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.9.3

  dep_cache:
    folder: vendor
    fingerprint_script: cat Gopkg.lock
    populate_script: dep ensure

  lint_script: golangci-lint run


test_task:
  env:
    CIRRUS_WORKING_DIR: /go/src/github.com/$CIRRUS_REPO_FULL_NAME

  container:
    matrix:
      image: golang:latest
      image: golang:1.9
      image: golang:1.10

  ci_tools_cache:
    folder: $GOPATH/bin

  get_dep_script: dep version || curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

  dep_cache:
    folder: vendor
    fingerprint_script: cat Gopkg.lock
    populate_script: dep ensure

  test_script: go test

docker_builder:
  only_if: $CIRRUS_BRANCH == 'latest' || $CIRRUS_BRANCH == 'stable'
  depends_on:
  - test
  - lint
  env:
    DOCKER_USERNAME: ENCRYPTED[60dbb7844e25362a784b72bce0581cb62c1878facb1ce6c79af0c5b23ddff049d90fc3237b886e9fb7ccbcf5ac973464]
    DOCKER_PASSWORD: ENCRYPTED[aa19d1b13c4c45c6bda1f837e7330b7514457a26d411a12993f4e8535cbc55b1d13e7ff6c78b4aa63edff97917891a4d]
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  build_script: docker build --tag docker.io/nstapelbroek/hostupdater:$CIRRUS_BRANCH --pull --build-arg VCS_REF=$CIRRUS_CHANGE_IN_REPO .
  push_script: docker push docker.io/nstapelbroek/hostupdater
  meta_script: curl -X POST ENCRYPTED[d0e9e2e67958eb7f9f12bb7257ff8875732026f58baef2693d270a75f122317bd7966512373cd04786c4043dc5db7841]
